### ISSUE TITLE
Model refit: epinephelus_aztecus

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#111]
I am having trouble understanding how to approach the analyses by epinephelus_aztecus. We might want to discuss this.

**Comment by troettge** [comment]
hm it is a structural equation model, so it is my understanding that it takes into account the observed variables AND unobserved latent variables. Later in the report they compare the coefficients to a series of regression coefficients and state that "Given the minimal discrepancies in estimation and other benefits of the use of SEM, we can again argue for the use of structural equation models."

So I see two options for us: 
1. Exclude from meta analysis
2. Rerun there individual models and add them to meta analysis

**Comment by stefanocoretta** [comment]
Let's go with 1.
