### ISSUE TITLE
Teams questionnaires

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#118]
- [x] Download latest version of intake questionnaires. [@jvcasillas]
- [x] Download latest version of peer-review questionnaires. [@jvcasillas]
- [x] Calculate team averages and merge with `msa_models`. [@stefanocoretta]

**Comment by jvcasillas** [comment]
I redownloaded all qualtrics forms. Only two changes which are now pushed to main via https://github.com/many-speech-analyses/many_analyses/commit/872928aa948b9f5ca884f13e797aa4df442d7175

**Comment by stefanocoretta** [comment]
- [ ] Download latest version of analysis questionnaire. [@jvcasillas]

**Comment by jvcasillas** [comment]
I downloaded this too (and everything). There were no diffs when I friend to commit.
