### ISSUE TITLE
Coding of individual predictors

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#120]
To get the Sørensen-Dice Index we need to code each analysis by indicating each individual predictor so that we can then create a matrix of present/absent for each predictor.

**Comment by troettge** [comment]
for reference: 

"Following Parker et al. (2020), the measure of uniqueness of predictors will be assessed by the Sørensen-Dice Index (SDI, Dice 1945; Sørensen 1948). The SDI is an index typically used in ecology research to compare species composition across sites. For our purposes, we will treat predictors as species and individual analyses as sites. For each pair of analyses (X, Y ), the SDI will be obtained using the following formula:

SDI= 2|X∩Y| |X|+|Y|

where |X ∩ Y | is the number of variables common to both models in the pair, and |X| + |Y | is the sum of the number of variables that occur in each model."

**Comment by troettge** [comment]
I have a feeling this won't be particularly useful, as teams had rather few predictors.

Questions I have:
- only population-level predictors or also random effects?
- is a model `y ~ typicality + gender` the same as a `y ~ typicality * gender` in terms of the SD index? (so how to deal with interactions)
- What about `typicality` vs `typicality_centered`? Two different ones or the same?

**Comment by stefanocoretta** [comment]
We are gonna code this in the analyses_coding sheet.

**Comment by stefanocoretta** [comment]
This task seems to be complete now.

@jvcasillas There is one mismatch between the number of predictors you reported and the number as given by the sum of the individual predictors matrix for gymnothorax_spinulosus. Could you have a look at it when you get the chance?

**Comment by jvcasillas** [comment]
Hmm not sure here. This is their model: 

```
fit0 <- lmer(measure ~ condition * typ_mean + 
    (1|target_colour) + 
    (1|speaker),
  data = gymnothorax_spinulosus_int, 
  REML = FALSE , 
  na.action = na.exclude
  )
```

Here is how I fit it: 

```
gymnothorax_spinulosus_1_intdiff_con <- brm(
  measure_z ~ effect_con * typ_mean_z + 
    (1|target_colour) + 
    (1|speaker), 
  data = MSA_gymnothorax_spinulosus_df, 
  cores = 4, threads = threading(2, grainsize = 100), 
  backend = "cmdstanr", seed = 06022016, 
  control = list(max_treedepth = 14), 
  file = here("data", "analyses", "models", "gymnothorax_spinulosus_1_intdiff_con")
  )
```

I coded it as 2 predictors, 3 terms, 5 coefficients (after subtracting 1). Looking at it again, this seems right to me. Any ideas what might be going on? @stefanocoretta

**Comment by stefanocoretta** [comment]
Ok, who did the coding of terms forgot `typ_mean_z` and the interaction, so now it matches. :)

**Comment by stefanocoretta** [comment]
All done now. I am gonna close this!
