### ISSUE TITLE
inconsistencies and questions about your coding

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#123]
I just coded the predictors for all models and came across some inconsistencies and issues we might want to resolve:

TR: I had a bunch of errors in my values for predictors, terms, coeff etc. So maybe double check yours as well.

SC: @stefanocoretta 
- #124
- [x] Why is neosilurus_omanensis model 3 excluded?
  - That was due to convergence issues while refitting which I could not fix, alas.
- #125 

JC: @jvcasillas 
- [x]  lasionycteris_altavela has a  `DV ~ effect_con` model, but you coded it as having 2 coefs. Did you generally count the intercept as well?
- [x] lycodes_bradfieldi: “processed data not available”, what do we do here? reach out?
- [x] gymnothorax_spinulosus: Their frequentist model includes an interaction, but you fit only a simple model. The number of terms in our sheet suggest you coded the interaction model with 2 predictors and 3 terms. Double check?
- [x] trigonias_lachneri: Their frequentist model indicates random slopes, you refit a model without them? Double check?
- [x] linckia_nattereri not done yet?
- [x] psittacula_scabriculus: number of coefficients = 3, but the model has just effect_cat. Double check?

**Comment by jvcasillas** [comment]
> lasionycteris_altavela has a DV ~ effect_con model, but you coded it as having 2 coefs. Did you generally count the intercept as well?

I know I already responded on slack, but I'll mention it again here. Yes, I always counted the intercept. I can go back and change mine, but we should probably see what @stefanocoretta did and then decide which would be less work (me changing mine to coincide with what you and stef did, or you changing yours to coincide with what stef and I did... stef what did you do?)

> lycodes_bradfieldi: “processed data not available”, what do we do here? reach out?

I have reached out. I will come back to this if I hear anything. 

> gymnothorax_spinulosus: Their frequentist model includes an interaction, but you fit only a simple model. The number of terms in our sheet suggest you coded the interaction model with 2 predictors and 3 terms. Double check?

This is an error and has been updated. The updated .rds file is now on OSF. 

> trigonias_lachneri: Their frequentist model indicates random slopes, you refit a model without them? Double check?

Another error. Fixed and the updated .rds file is now on OSF. 

> linckia_nattereri not done yet?

This is a logistic regression model with 10 predictors. I recall talking about htis before and I think we decided to exclude it. Does that sound right?

> psittacula_scabriculus: number of coefficients = 3, but the model has just effect_cat. Double check?

This is correct. The model estimates 3 pop-level coefficients. `effect_cat` has three levels so the model estimates the intercept, plus `effect_catmedium` and `effect_cattypical`.

**Comment by stefanocoretta** [comment]
> lasionycteris_altavela has a DV ~ effect_con model, but you coded it as having 2 coefs. Did you generally count the intercept as well?

I did not count the intercept, so maybe @jvcasillas you can just reduce your counts by 1?

**Comment by jvcasillas** [comment]
> > lasionycteris_altavela has a DV ~ effect_con model, but you coded it as having 2 coefs. Did you generally count the intercept as well?
> 
> I did not count the intercept, so maybe @jvcasillas you can just reduce your counts by 1?

Got it! I will subtract 1 from all of mine. @troettge @stefanocoretta

**Comment by jvcasillas** [comment]
RE `linckia_nattereri` = EXCLUDE

**Comment by troettge** [comment]
in the msa_models dataframe are two estimates that are >20. Must be an error somewhere. Need to check.

**Comment by jvcasillas** [comment]
> More questions:
> 
> in the msa_models dataframe are two estimates that are >20. Must be an error somewhere. Need to check: polymetme_brevirostrum model #1

I double checked to see if this was one of mine (it wasn't), so after @stefanocoretta check into this we can talk about whether there is an error on our end or if the team did something weird. 

> if you plot data vs. posteriors for the predictor model it becomes clear that the model is extremely confident and I think this is due to the complete lack of random effects in the predictor model. We have talked about this, but I am not sure we decided to just ignore these important dependencies. Can some remind me on why the `predictors_bm` model has no random intercepts at least?

I'd like to talk about this as well. My meta-analysis experience is pretty limited (just two), but the tutorials/sources I use don't say anything about not using random effects (not that I recall). We can come back to this to be sure and learning something new, I bet.

**Comment by troettge** [comment]
I mean the second model with the predictors is just a multilevel model right? What is meta about that? It should obey simple lm assumptions including independence. 

![image](https://user-images.githubusercontent.com/13022447/184351632-d3b0f5d6-1558-4d0c-9e29-1ed8f289f172.png)
Treating these data points as independent is a krass violation AFAIK.

**Comment by stefanocoretta** [comment]
Yes, we talked about this and decided to include a random intercept. I just didn't have the time to change it yet.

But if you want to go ahead and add it, please do.

**Comment by stefanocoretta** [comment]
For the future it would be great if you could have one question/point per issue, because it's difficult to keep track of everything if it's all in one issue.

**Comment by troettge** [comment]
changed it and pushed it
