### ISSUE TITLE
Picking priors for Bayesian models after scaling

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#125]
Timo said

> I noticed that when analysts used priors and you scaled the model you also used weakly informative priors. You noted you were unsure what to do. I had the same issue and then just opted for default priors. We should be consistent with that. So either we do default priors or we scale their priors. What do you guys think?

**Comment by stefanocoretta** [comment]
THat's a good point! I think the easiest option is to use default priors as you did.

**Comment by troettge** [comment]
I think that only applies to your models @stefanocoretta. If you find time, @jvcasillas, could you rerun his Bayesian models with default priors and store the models as usual?

**Comment by stefanocoretta** [comment]
I can fix this now!

**Comment by stefanocoretta** [comment]
Done!
