### ISSUE TITLE
polymetme_brevirostrum model output off

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#126]
In the msa_models dataframe are two estimates that are >20 (one is over 120). Must be an error in the recoding somewhere. Need to check: polymetme_brevirostrum model #1

@stefanocoretta

**Comment by troettge** [comment]
@jvcasillas can you check this one out for me? It's in Stefano's pile.

**Comment by stefanocoretta** [comment]
I am having a look at this now.

**Comment by stefanocoretta** [comment]
Ah I remember this was problematic, because there is `Condition * effect_cat` but many of those combinations don't exist in the data (i.e. type of focus condition * typicality, which was varied only in NF condition).

I have updated the coding sheet on gdrive to reflect this.
