### ISSUE TITLE
Meeting 2022-08-16

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#127]
- [x] Timo walks through results section (so far)
- [x] discuss plots
- [x] make to do list

some of TRs notes:

- fix coding and redownload
- the continuous predictors pull the meta estimate down to very small values so it is hard to speak about the numerical value in context. 
- report on compelling results (95% CrI not overlapping with zero) or as reported as significant by analyst or both?
- we preregistered posthoc shenanigans as predictor, but not really useful

To do:

- [x] #131 
- [x] #129
- [x] #128 
- [x] #130

**Comment by stefanocoretta** [comment]
`msa_models.rds` and code is now up to date.

You can re-run the meta-models in `05_meta-analysis.Rmd`. We still have two pending issues to discuss but changes should be minor:

- #125 
- #126

**Comment by troettge** [comment]
@stefanocoretta did you push all changes? you store "./data/meta_analysis/meta_bm.rds" which I cannot find anywhere
