### ISSUE TITLE
meta and results branch diverge

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#132]
The branches `meta` and `results` are currently divergent. Which one are we working with?

I will merge everything so that we can work on a single branch.

Maybe we can just use main now?

**Comment by stefanocoretta** [comment]
Here's the current state

<img width="832" alt="Screenshot 2022-08-17 at 10 43 38" src="https://user-images.githubusercontent.com/6429302/185087868-dabf116a-e051-431c-8ba0-36832699e465.png">

**Comment by troettge** [comment]
yeah i realized, gimme a second, to push my changes!

**Comment by troettge** [comment]
okay all up now, lemme know when you have merged

**Comment by stefanocoretta** [comment]
Of course you also made changes to master so plenty of conflicts to deal with :D Anyway, now everything is fine, but I have renamed `master` to `main`. 

The easiest thing to do is for you to delete your current local repository and clone it again from scratch, or more conflicts will emerge.
