### ISSUE TITLE
predictor model

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#133]
I am wondering now tho; years after phd, prior belief, teams number of models and peer ratings are all aspects of the team, and should be covered by the random intercept right? so we build a model here that has to divide explained variance between rintercept and predictors. That's no bueno, am I right?

**Comment by stefanocoretta** [comment]
I am lost.

A random intercept by team (`animal`) should account for the fact that most teams have submitted more than 1 analysis. But that deviates from what we have preregistered.

Shouldn't we just stick to the preregistration and then discuss potential pitfalls in the discussion? I feel we are playing with RDFs somewhat.

**Comment by troettge** [comment]
I don't think dropping the intercepts is a good idea at all. The model without intercepts is extremely flawed because it confounds predictors with teams, e.g. the team with 16 models is the only one with 16 models and those 16 models will pull the estimate hard for that predictor if the model thinks these are independent data points. We need rintercept IMO. So I vote strongly for including intercepts because else, all team-level predictors are uninterpretable so the model is complete trash. Maybe the issue I noted here is not that much of an issue, certainly not as much as not including proper random effects.

**Comment by stefanocoretta** [comment]
Then we should have both the pre-registered model without random intercept and a model with it, so we can compare (especially in light of what the editor has told us via email a few minutes ago).

**Comment by troettge** [comment]
Yeah I think we should make one Rmarkdown with all the originally planned models and an explanation of why we changed what we changed. I am not worried, our RR is too descriptive to be in danger of being rejected at stage 2

**Comment by jvcasillas** [comment]
I agree re including the random intercept. It's true that we didn't pre-register it, but we also said we would only take one estimate per team. Thus, it seems to me like the only reasonable thing to do, if we are going to allow for multiple data points from teams. I have no qualms with making this change and explaining why. In fact, I think this is an important part of the story (i.e., we told teams to pick one, and practically all of them ignored that).

**Comment by stefanocoretta** [comment]
So have we settled on including the random intercept in the end? If so, can we close this issue?
