### ISSUE TITLE
estimation error gymnothorax_spinulosus

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#134]
new outlier: estimate of -225, please check! @jvcasillas

**Comment by troettge** [comment]
yeah there are some errors in the refitting code:

```
MSA_gymnothorax_spinulosus_df <- gymnothorax_spinulosus_int %>% 
  mutate(measure_z = (measure - mean(measure)) / sd(measure),
    effect_con = (typ_mean - mean(typ_mean)) / sd(typ_mean), 
    typ_mean_z = (typ_mean - mean(typ_mean)) / sd(typ_mean)) %>% 
  filter(condition == "AF")

gymnothorax_spinulosus_1_intdiff_con <- brm(
  measure_z ~ effect_con * typ_mean_z + 
    (1|target_colour) + 
    (1|speaker), 
  data = MSA_gymnothorax_spinulosus_df, 
  cores = 4, threads = threading(2, grainsize = 100), 
  backend = "cmdstanr", seed = 06022016, 
  control = list(max_treedepth = 14), 
  file = here("data", "analyses", "models", "gymnothorax_spinulosus_1_intdiff_con")
  )
```

You somehow included in interaction of typicality with typicality. i am fixing it right now.

**Comment by troettge** [comment]
Also I cannot see why you excluded "AF" here. Don't see that in the original script??

**Comment by troettge** [comment]
Please double check, change code to, and re-upload everything:

`MSA_gymnothorax_spinulosus_df <- gymnothorax_spinulosus_int %>% 
  mutate(measure_z = (measure - mean(measure)) / sd(measure),
    effect_con = (typ_mean - mean(typ_mean)) / sd(typ_mean), 
    condition_s = as.factor(condition),
    condition_s = C(condition_s, sum))
#  filter(condition == "AF")

gymnothorax_spinulosus_1_intdiff_con <- brm(
  measure_z ~ effect_con * condition_s + 
    (1|target_colour) + 
    (1|speaker), 
  data = MSA_gymnothorax_spinulosus_df, 
  cores = 4, threads = threading(2, grainsize = 100), 
  backend = "cmdstanr", seed = 06022016, 
  control = list(max_treedepth = 14), 
  file = here("data", "analyses", "models", "gymnothorax_spinulosus_1_intdiff_con")
  )`

Also check if your refit_jc.Rmd script runs through, doesn't for me.

**Comment by jvcasillas** [comment]
> You somehow included in interaction of typicality with typicality. i am fixing it right now.

> Also I cannot see why you excluded "AF" here. Don't see that in the original script??

These are both mistakes (good catches). The first was silly copy/paste error and the second one I was testing something and forgot to delete it. In any case, yes, I can knit the document fine, but I cant pull in the most recent changes. I'm getting a weird error I've seen before when I try to update the repo. In any case, I uploaded the new RDS file to the OSF.

**Comment by jvcasillas** [comment]
Uggh... it's because I tried pushing to master... not realizing it had been renamed to main. This looks like it might be a cluster fuck. I'll come back to it in the morning, but yeah, the correct model for gymnothorax_spinulosus is on OSF now.
