### ISSUE TITLE
model predictions fucked up

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#135]
Ran the monster model, took almost 3h with my machine and did not converge nicely (Warning: 9525 of 16000 (60.0%) transitions hit the maximum treedepth limit of 15)

![alltogether](https://user-images.githubusercontent.com/13022447/185148813-ae933af5-d8fa-428f-acbb-b6a46f31d6a1.png)

What is comforting is that nothing turns out to be relevant, except for f0 and n_random (= model conservativeness). n_random makes little sense though giving the raw data. Running a simple linear model on estimate ~ n_random give absolutely no signal, so it is not even that one outlier that explains it. Then again, its a measurement error model right? So is the model just crap because of convergence issues? Need to have a look into this.

**Comment by stefanocoretta** [comment]
I believe this is being discussed here: #136.
