### ISSUE TITLE
conservativeness predictor totally off

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#136]
check 05_meta_analysis.RMD line 545 and following and tell me what I am doing wrong OR why the model is so bad for the conservativeness predictor:

![image](https://user-images.githubusercontent.com/13022447/186123352-87cd15ea-aeac-4473-a215-003b00996f7d.png)

**Comment by troettge** [comment]
I think it could be due to dummy coding of categorical predictors. Should use contrast coding here as well, else it probably estimates it for measurement = other and window = other? Sth to discuss

**Comment by troettge** [comment]
it has clearly to do with the measurement error. If you run the same model only on the estimate, the effect becomes much smaller and makes sense relative to the data.

**Comment by troettge** [comment]
Now if you run the entire model as a normal model predicting estimates you get this:

![image](https://user-images.githubusercontent.com/13022447/186361069-18e576d5-e23f-4018-afc9-f220d374a06c.png)

This makes more sense and is still conservative enough. So if we don't figure out what the fuck is happening with measurement error model, I'd suggest using this model (saved as `predictors_bm_rintercepts_only_est.rds`)

**Comment by jvcasillas** [comment]
wtf??? hmm at least now we have a good idea of where the problem is

**Comment by troettge** [comment]
https://twitter.com/fusaroli/status/1562499912742633474

okay as far as I understand it, the ME model weighs estimates with less uncertainty more heavily and shrinks those with high uncertainty towards the pooled mean. That is a problem with our model because it literally confounds the ME component with the predictor for conservativness. Because models with high n of random terms are more uncertain, they matter less and will be shrunk to the mean, while those with lower n of random terms are more certain and will contribute more to the population estimate. I think this is literally really biasing the results for that predictor. So I think this is actually a good statistical argument not to include this predictor.

**Comment by jvcasillas** [comment]
That's a useful thread. I'm not totally convinced (yet), but I'm going to study this a bit more and compare with some of my resources.

**Comment by stefanocoretta** [comment]
If I understood everything correctly (and I am not sure I did), it seems that indeed the SE and number of random terms should be in principle correlated and hence be a problem when both are included in the model.

**Comment by stefanocoretta** [comment]
Where are we at with this, @troettge? Have you refit the model without that predictor and saved the output?

**Comment by troettge** [comment]
refit model and saved output! Close!
