### ISSUE TITLE
Obtain mean and SD for outcome variables from all submitted models

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#144]
It would be great if we could get the mean and SD for each outcome variable used in the models submitted by the teams.

The SD will allow us to talk about group-level differences in terms of actual acoustic measures.

The estimated SD for group-level deviations from the meta-analytic estimate is between 0.11-0.15 at 95% confidence. So we can multiply those estimates and the outcome measures SD to obtain a concrete estimate of what kind of differences we talk about in terms of acoustic measures.

**Comment by jvcasillas** [comment]
@troettge the team `` (osf: https://osf.io/sf5z9/) has no analysis scripts. According to your code in `refit_tr.Rmd` there is definitely R code and there should be a directory called `trial_level_data`. I see none of this, which makes me think it was erased/overwritten somehow. The recent activity section has 17 tabs of shinnanigans but Im not about to go through it. So... 1) can you confirm that this is some kind of mistake here and 2) do you happen to still have the original files locally?

**Comment by troettge** [comment]
puh in the meanwhile we have recloned the repository several times and probably lost some of those. I think the project is by Marton soskuthy, meaning I doubt there is something missing. Let me dig

**Comment by troettge** [comment]
@stefanocoretta Something is off here. It seems like the repo of this team was substantially changed ... by you? Can you look into this, because all their data, report etc. are gone!

**Comment by stefanocoretta** [comment]
You need to be logged in into OSF and then you'll see the GH repo too.

**Comment by troettge** [comment]
<img width="1664" alt="Screenshot 2022-09-08 at 10 39 19" src="https://user-images.githubusercontent.com/13022447/189076625-cda5d688-7a54-444c-b83a-6edb1a01d349.png">
 
Logged in, don't see it!

**Comment by stefanocoretta** [comment]
Can you try now?

**Comment by jvcasillas** [comment]
I see it now and I am able to access the files. Shall we move them to the OSF component as well (for reproducibility)?

**Comment by stefanocoretta** [comment]
Why not!

**Comment by stefanocoretta** [comment]
Done with #155

**Comment by stefanocoretta** [comment]
@jvcasillas Thanks for doing this! I was looking at the values and I think in some cases the teams have used logs (so I see for example in anthracoceros_coronata hwere duration is in logs rather than ms).

Could you perhaps go through them and check this? You might have to convert logs back to ms or what not and do SD on that. (I don't think you can transform SD logs back without the original data, right?). I would do it but I would have to download all the data and it's taking ages :D

**Comment by jvcasillas** [comment]
Just to double check on this one... some of the measures are log transformed (and later we standardize them when we refit). You are saying we should get the mean and SD of the values before the log transformation? Are we certain this is what we want? Some measures are completely derived from these transformations. For example...

```
f0.clean <- f0.clean %>% 
  ungroup() %>% 
  group_by(speaker) %>% 
  mutate(f0min = min(f0)) %>%
  mutate(f0sem=(12*log(f0 /f0min))/log(2)) %>% 
  ungroup()
```

In this case, the DV later used in some of the models is `f0sem`. We can talk about the mean and sd of `f0sem` without problems and relate this back to the researchers original model. In this case are suggesting I get mean/sd of `f0` or `f0min`? It seems like the most useful thing for us would be to have the mean/sd of whatever they used in their model, but perhaps I still haven't completely understood what we need and why we need it. @stefanocoretta @troettge

**Comment by stefanocoretta** [comment]
Right, it's simple by being complex. Easier to chat if you have time. I am free later today.

**Comment by jvcasillas** [comment]
This is going to be a lot more work, Im afraid.

**Comment by troettge** [comment]
not sure this is worth the hassle, but maybe that is just me, we could ground the SDs in an external more controlled dataset or we could ignore those that have created crazy chains of transformation.

**Comment by jvcasillas** [comment]
It looks like it is 6 teams (of 29) where this is going to be the case. I will go through it this afternoon and see if I can work my way back to the raw values in all the cases.

**Comment by stefanocoretta** [comment]
Following up on my chat with Joseph, he will screen the values and make a judgement on which ones to keep and which ones not to, so this is being sorted out.

**Comment by stefanocoretta** [comment]
Hi @jvcasillas ! Can you close this when done?

**Comment by jvcasillas** [comment]
Will do. i'm going to give it one last look through within the hour.
