### ISSUE TITLE
Using nested group-level effects for team and model ID

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#147]
Sorry that I bring that up again. I thought about it yesterday, but couldn't formulate my thought. Our first model is still bad because it does ignore dependency between teams. 

What we should do IMO is a nested random effect structure that nests model in teams (1 | mode | team). Am I wrong?

**Comment by stefanocoretta** [comment]
Here's the model summary:

```
 Family: gaussian 
  Links: mu = identity; sigma = identity 
Formula: estimate | se(se) ~ (1 | animal) + (1 | animal:model_id) 
   Data: msa_models (Number of observations: 170) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Group-Level Effects: 
~animal (Number of levels: 30) 
              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)     0.02      0.01     0.00     0.05 1.02      334      677

~animal:model_id (Number of levels: 170) 
              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)     0.13      0.01     0.11     0.15 1.00      893     1402

Population-Level Effects: 
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept     0.01      0.01    -0.01     0.04 1.01      450      802
```

**Comment by troettge** [comment]
so basically doesnt make a difference?

**Comment by troettge** [comment]
Should we then not use the nested model instead? That makes the justification for our change even more palatable because we keep teams and can discuss variation between teams and models?

**Comment by stefanocoretta** [comment]
Yes, but let's keep the original model in and talk about the nested one in the non-preregistered bit. It's easier at this stage (= less work)

**Comment by troettge** [comment]
can you briefly elaborate on that? What makes it more difficult to add this nested model? I would be more comfortable with a model that does not obviously violate independence (since we call that out in the discussion). If you can point me to how adding the nested model creates extra work and what exactly, we can evaluate if its worth our time.

**Comment by stefanocoretta** [comment]
The nested one will be there, so no problem with the violation of independence. I'll take care of this!
