### ISSUE TITLE
instruction to submit one model

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#148]
I thought there were instructions to submit only one result, right? I want to make a point out of fact that teams submitted multiple attempts to answer the research question. Where was that instruction?

**Comment by jvcasillas** [comment]
I went back and checked the language we used in the qualtrics survey and we asked for the effect size (in singular) and the dependent variable, but we did not say something to the effect of "pick one". That said, we did say that in the zoom meeting with all the participants (we have that recording too, if I'm not mistaken).

**Comment by stefanocoretta** [comment]
Yes, although after that, given that many have raised the concern that picking one would not be possible, the instructions I sent later on via email just asked to submit the analysis (as far as I can remember). So in the end we didn't enforce the constraint of picking and submitting just one day thing.

**Comment by stefanocoretta** [comment]
If there's no pending issues, we can close this.
