### ISSUE TITLE
Forest plot of shrunken effect sizes

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#152]
The forest plot of the shrunken effect sizes (as returned by the meta-analytic models) is slightly different in the `model_id` model vs the `team/model_id` model

`model_id`

![](https://github.com/many-speech-analyses/many_analyses/raw/results-sc/figs/meta_plot1.png)

`team/model_id`

![](https://github.com/many-speech-analyses/many_analyses/raw/results-sc/figs/meta_plot1_nest.png)

Which one do we include in the RR?

**Comment by jvcasillas** [comment]
I would vote for the model that is justified by the nested nature of the data.

**Comment by troettge** [comment]
Second that, the nested model is IMO more appropriate

**Comment by stefanocoretta** [comment]
Great!
