### ISSUE TITLE
Coding error in refit_tr.Rmd

### ISSUE THREAD

**Issue by jvcasillas** [many-speech-analyses/many_analyses#153]
Lines 1502-1524 of `refit_tr.Rmd` run the same model twice: 

````
dunkleosteus_inscriptus_4_adur_cat <- brm(
  dur_a_s ~ 
         effect_cat + 
         (1|speaker) + 
         (1|target_name) + 
         (1|target_colour),
  seed = 111,
  data = dat, 
  cores = 4,  
  file = "./data/analyses/models/dunkleosteus_inscriptus_4_adur_cat"
  )
  
dunkleosteus_inscriptus_5_npdur_cat <- brm(
  dur_a_s ~ 
         effect_cat + 
         (1|speaker) + 
         (1|target_name) + 
         (1|target_colour),
  seed = 111,
  data = dat, 
  cores = 4,  
  file = "./data/analyses/models/dunkleosteus_inscriptus_5_npdur_cat"
  )
````

I believe the second model should have `dur_np` as the DV (judging by the name of the model object).

**Comment by jvcasillas** [comment]
I will update the code on the `jvc-sd` branch and include the change in the next PR. I will upload the correct model to OSF by hand.

**Comment by jvcasillas** [comment]
Fixed via https://github.com/many-speech-analyses/many_analyses/pull/155. Updated model is now on OSF. This can be closed whenever 👍🏼

**Comment by troettge** [comment]
thanks! Good catch again!
