### ISSUE TITLE
Model label correspondence error in refit_tr.Rmd

### ISSUE THREAD

**Issue by jvcasillas** [many-speech-analyses/many_analyses#154]
The google sheet where all models are coded lists the 8 models of `pervagor_meeki` as seen here: 

```
animal		model_n outcome operationalization  speci…⁸ 
pervagor_meeki  1 	intens… mean                noun    
pervagor_meeki  2 	durati… NA                  noun    
pervagor_meeki  3 	f0      mean                noun    
pervagor_meeki  4 	f0      max                 noun    
pervagor_meeki  5 	intens… mean                adject… 
pervagor_meeki  6 	durati… NA                  adject… 
pervagor_meeki  7 	f0      mean                adject… 
pervagor_meeki  8 	f0      max                 adject… 
```

The `model_n` column does not correspond with the actual models as they are coded in `refit_tr.Rmd`. The mislabeled models are the following: 

- pervagor_meeki_2_f0meannoun_cat (model_n = 2, should be duration of the noun according to the sheet, but is mean pitch `Mean_f0_st_s`)
- pervagor_meeki_3_f0maxnoun_cat (model_n = 3, should be mean pitch according to the sheet, but is max pitch `Max_f0_st_s`)
- pervagor_meeki_4_durnoun_cat (model_n = 4, should be max pitch according to the sheet, but is duration of the noun `Duration_ms_s`)
- pervagor_meeki_6_f0meanadj_cat (model_n = 6, should be duration of the adj according to the sheet, but is mean pitch `Mean_f0_st_s`)
- pervagor_meeki_7_f0maxadj_cat (model_n = 7, should be mean pitch of the adj according to the sheet, but is max pitch `Max_f0_st_s`)
- pervagor_meeki_8_duradj_cat (model_n = 8, should be max pitch according to the sheet, but is duration of the adjective `Duration_ms_s`) 

If it isn't clear, this is a problem because the model labels need to match up with the model_n in the sheet so that we can pair the mean/sd info with the correct DV. I suggest refitting the models with the correct names (according to the google sheet) and uploading manually to OSF. Alternatively, we could just update the info in the google sheet to match the actual models, but I won't do anything until somebody else chimes in (I haven't thought through what other possible downstream consequences there could be).

**Comment by troettge** [comment]
@jvcasillas good catch, I remember this was the first one and I had to scramble around. Since I recloned the repo without the data, could you refit them accordingly. Really good catch (I know there are probably some fuck ups, damn this also might change the interpretation of the predictor model, but glad we found it.)

**Comment by jvcasillas** [comment]
Fixed via https://github.com/many-speech-analyses/many_analyses/pull/157

Updated model with correct labels have been manually uploaded to OSF.
