### ISSUE TITLE
duplicate models

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#158]
Annnnd another data hick-up: there are 12 duplicate model_ids, all from pervagor_meeki

`msa_models[which(duplicated(msa_models$model_id)),]`

What's that about? Looking at my refit script, I only fitted 8 models not 14. 

I noticed it when plotting. Seems to be related to the ones Joseph fixed for me. Maybe we didn’t delete the old models?

**Comment by jvcasillas** [comment]
aita a multivariate model. Stef refit then individually to get the estimates and coded them as part of the same model (correct me if i'm wrong). There are 2 like this.

**Comment by jvcasillas** [comment]
Ahhh ignore above comment. I misunderstood. I uploaded the new models to OSF. Its possible that they were all saved when redownloaded? Not sure.

**Comment by troettge** [comment]
did you delete the models that I had fit (under the wrong naming)?

**Comment by jvcasillas** [comment]
> did you delete the models that I had fit (under the wrong naming)?

Locally I didnt delete anything because I never had them. Let me double check on OSF real quick.

**Comment by jvcasillas** [comment]
Yes, this is exactly what happened (oops!). Fixing now.

**Comment by jvcasillas** [comment]
Ok. I deleted the older ones. Good catch! Should be fixed now.

**Comment by stefanocoretta** [comment]
@troettge you can rerun the meta-models by rendering the Rmd files in `scripts/r` number `04-1`, `05`, and `06`.

**Comment by troettge** [comment]
so I download all refitted models again, right? on it
