### ISSUE TITLE
New results version +inf

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#160]
Here are the new results after fixing the latest glitch. Really awesome because dependent on measurement outcome, we now get compelling positive or negative effects :eyes:

(I remain a little bit skeptical to the brittleness of our model though)

![alltogether](https://user-images.githubusercontent.com/13022447/189515276-bf3ec7ca-d0f5-4528-8491-75f66b95fc99.png)

**Comment by jvcasillas** [comment]
How convinced are you that the model is actually brittle? In plots a and b the estimate we chose to talk about is slightly different, but its still a small effect. Its not like we make drastically different claims. I think I would be more concerned if we were getting big changes when including/excluding a key predictor, which I don´t consider to have been the case with our multicollinearity issue. Getting funky results when we make errors is something different imo.

**Comment by troettge** [comment]
Its just that certain predictors shifted around just by virtue of some coding errors, which makes me a little uneasy, but if we manage to stay humble, its all good!

**Comment by stefanocoretta** [comment]
I agree with Joseph: if results change because of errors, that tells us anything about the robustness of the model. Robustness as I see it is in relation to degrees of freedom, not errors. (In other words, how could a statistical model be made so that it is not led astray by genuine errors? If that were possible, then we would live in a perfect world).

**Comment by stefanocoretta** [comment]
If anything, the model is quite robust since we have made several specification adjustments and very little has changed from an overall perspective.

**Comment by troettge** [comment]
I am okay with it and agree
