### ISSUE TITLE
tenzing contribution

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#162]
Just started a google sheet for contributorship and sent you an invite (lemme know if now received).

I added you guys plus Simon Roessig and Michael Franke to the list (Simon ran the original experiment with me, Michael funded and ran the norming study, both I think warrant authorship, but open to discuss of course). Should we make all authors sign in their email address, affiliation and ORCID? We could block the tick boxes or tell them that they contribution only constitutes "investigation" and "writing, review and editing".

**Comment by stefanocoretta** [comment]
Did not get a notification but I can see. Although, Timo can you please move it into the `many_analyses_docs` folder on GDrive, since all the other documents are there? Thanks

**Comment by troettge** [comment]
moved to Gdrive

**Comment by jvcasillas** [comment]
I ticked the box for the 3 of us for software. I looked it up on the credit website and it includes writing code. Feel free to untick if you disagree.
