### ISSUE TITLE
Update after edits

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#166]
I have worked on the draft which slowly comes into shape. I violantly edited, drafted a conclusion section and tidied up some lose ends.
I see two major flow problems:

1. reporting three different models (preregged with team as random, non-preregged with model as random and one with model nested in team as random). I chose to talk only about the preregged and non-preregged nested model. See if that makes sense
2. reporting the grounding in SDs. Complex process, hard to communicate. So I simplified it quite a bit and moved it into the discussion section.

Beyond that there are some minor ToDOs (should all be visible as comments in the draft):

_Descriptive Results_
- [x] Make table for team characteristics (was that your task @jvcasillas ?
- [x] add reasons for why teams dropped @stefanocoretta [7e4f1e5](https://github.com/many-speech-analyses/many_analyses/commit/7e4f1e5a39edadcad11d41c1ed676bed9610c55a)
- [x] double check that all proportions refer to models and not to coefficients. I am thinking about the acoustic measures and statistical choices part. If we used rows as the denominator we might skew the numbers towards those models who used categorical outcomes. d7facc6
- [x] check number of linear models vs. others (including GAMS). I counted 9 GAMS in the coding sheet, wondering how it amounts to only 2% d7facc6
- [x] add section at end of statistical analysis on how many analyses claim to have found a statistically reliable effect (number / models) and how many teams have claimed at least one found effect. Need to redownload the edited coding sheet.

_Meta-analytic estimation_
- [x] add background info and use consistent terminology  (SC comment)
- [x] outsource table for all SD estimates and focus only on one example: duration. Maybe we could make a vignette for this? dunno
- [x] add/edit reference to JND
- [x] describe a second phenomenon that makes theoretical claims based on 7-15ms difference, ideally from articulation?

_Analytic and researcher-related predictors_
- [x] extract and fill in estimates and 95% CrIs as indicated in text

_Discussion_ 
- [x] add ref to "process and statistical model" in McElreath (SC comment)
- [x] MFA, Formant tracking etc (SC comment)

_Language_
- [x] check 1st person plural. I think it is more matter of fact if we talk in 3rd person when we talk about researchers. I know the gist behind using "we/us" but it confuses me as a reader who needs to joggle what WE, the MSA project, have done, and what they, the analysts, have done and what they, researchers in general, ought to do. Up to you, just needs to be consistent.
- [x] check tense (present vs. past) when reporting results.

Afterwards we all need to read through the whole MS again and push a last round of edits, then out to teams
- [x] joseph
- [ ] timo
- [x] stefano

**Comment by jvcasillas** [comment]
Here's a first go at a table of descriptives. I was throwing in basically everything I could think of (figured put it all in and then take things out). What else could/should I add? Also, the labels in the metric column are just the first things that came to mind... better labels coming (add suggestions). 

<img width="843" alt="Screen Shot 2022-09-19 at 7 09 39 AM" src="https://user-images.githubusercontent.com/1747068/191005243-07f9d100-6254-4479-9e76-22d0fc1829bf.png">

**Comment by troettge** [comment]
@jvcasillas this is great. 
- generally maybe round to one decimal across the board (maybe just me but seing 33 next to 93.33 makes my brain hurt)
- maybe we can typographically group phon rating, stats rating, and their average
- we don't really talk about H1 in manuscript, maybe just in plausibility of relationship or sth?
- number of team members per group could be useful here too
- maybe the main outcome choices (f0, int, dur, others) as well as time windows because that is the unique aspect of our study? Could group that under measures

**Comment by jvcasillas** [comment]
@troettge I just saw your comments after submitting a PR. I actually did a few of them already (e.g., decimal places) and covered a some other things in a separate table. Take a look at the updated PDF and let me know what you think should change.

**Comment by jvcasillas** [comment]
I just pushed this... it's big, but I kinda like it. 

<img width="653" alt="Screen Shot 2022-09-23 at 1 20 13 AM" src="https://user-images.githubusercontent.com/1747068/191896454-516972ff-93e8-49ab-a81c-ae58bc200b22.png">

**Comment by jvcasillas** [comment]
Remaining estimates and CrIs included via https://github.com/many-speech-analyses/many_analyses/pull/171

**Comment by troettge** [comment]
Looks great. One question: Are these only the "included" teams? Because I remember we had more GAMS than 1 (also more ML than 1). Maybe this graph should reflect all teams who submitted rather than only the ones we included? (if that is what happened here)

**Comment by jvcasillas** [comment]
> Looks great. One question: Are these only the "included" teams? Because I remember we had more GAMS than 1 (also more ML than 1). Maybe this graph should reflect all teams who submitted rather than only the ones we included? (if that is what happened here)

Yes, this is included teams (submitted analyses)... so 30 teams.

**Comment by jvcasillas** [comment]
I think youre right (that we should have descriptives on all teams that submitted something, not just the ones included in the MA), but should it be in the main text? When we talk about some of these measures, particularly the ones included in the models as predictors, I think it makes more sense to know the characteristics of what was actually included. Am I making sense?

**Comment by stefanocoretta** [comment]
Yes, one of my comments in the draft is about that. I think we should report info of both all submitted analysis and only the included ones. Joseph can you work on that?

**Comment by troettge** [comment]
yeah you are making sense, maybe we can describe all teams for team characteristics and acoustic measures plus model types and inference frameworks, but zoom in on linear models for the statistic on predictors etc.?

**Comment by troettge** [comment]
love the table, here is some additional feedback on table @jvcasillas 
- is the peer rating the overall rating or the statistical analysis rating? Maybe it is clearer if we have acoustic analysis rating and statistical analysis rating?
- the stats analysis part, I am not completely clear and what refers to what. Coefficients are population-level coefs? random effects are random terms? and what are "terms"? Maybe we can find more descriptive references here

**Comment by jvcasillas** [comment]
> Yes, one of my comments in the draft is about that. I think we should report info of both all submitted analysis and only the included ones. Joseph can you work on that?

I'm working on this now. I will create both tables and we can figure out how to deal with them/where to put them after. 

> is the peer rating the overall rating or the statistical analysis rating? Maybe it is clearer if we have acoustic analysis rating and statistical analysis rating?

Peer rating is overall rating of the teams analysis. Statistical rating is self-report. 

> the stats analysis part, I am not completely clear and what refers to what. Coefficients are population-level coefs? random effects are random terms? and what are "terms"? Maybe we can find more descriptive references here

I am going to use the descriptions from the google sheet to try to come up with some better labels. We probably need to remove one or two.

**Comment by jvcasillas** [comment]
Ok, I simplified the model part, removing the stuff that didn't really make sense or add value. @troettge I fixed labels to clear up what the ratings imply. All the numbers match what is reported in prose, which I think is important. This why it only includes data from teams that submitted analyses that were included in the meta-analyses (otherwise the values won't match). I propose including another table with all submitted analyses (i.e., those that were and were not included in the MA) for the supplementary materials. Another table of this size would be confusing, I think. Thoughts?

<img width="743" alt="Screen Shot 2022-09-24 at 7 46 49 AM" src="https://user-images.githubusercontent.com/1747068/192096419-c616a761-f8b7-4c79-aef1-4c8fabad189a.png">

**Comment by troettge** [comment]
This looks good! I am still confused about numbers. So there were X teams who signed up and only a Y amount of teams submitted in times. I thought Y = 30. But we also excluded a bunch of submitted analyses from the meta analysis. That information does not show up anywhere or am I wrong? Help me unknot my brain here.

**Comment by stefanocoretta** [comment]
Yes, I think a table like this one but with all submitted (rather than just included) would be nice to have in supplementary materials.

Yes, 30 teams are the ones that we included, but there are a few more who submitted. We need to update this bit in the RR to make it clear. Can one of you do that?

**Comment by jvcasillas** [comment]
This bit here explains most of the story. I'll explain that some submitted analyses couldn't be included in the MA. 

![image](https://user-images.githubusercontent.com/1747068/192099279-5d073cfa-45da-42f1-b887-8a5cf1202991.jpeg)

**Comment by jvcasillas** [comment]
I have created `supplementary_materials.Rmd` and included the monster table with data from all submitting teams. It's pretty cool. Take a look here: https://github.com/many-speech-analyses/many_analyses/blob/jvc-sd/RR_manuscript/supplementary_materials.pdf 

I will continue editing tonight and submit a PR tomorrow morning.

**Comment by jvcasillas** [comment]
JVC todo

- [ ] fix 'machilearning' typo
- [ ] explain why 30 teams are included
- [ ] refer to supp materials for data from all submitting teams

**Comment by jvcasillas** [comment]
I believe (all) the table stuff is now complete and included via https://github.com/many-speech-analyses/many_analyses/pull/176. 

I keep finding small typos and stuff as a read so one final read through with fresh eyes is necessary (for me).

**Comment by jvcasillas** [comment]
My final (maybe) edits are in via https://github.com/many-speech-analyses/many_analyses/pull/176 and https://github.com/many-speech-analyses/many_analyses/pull/178. 

A couple of notes: 

- crossrefs don't seem to work, e.g., \@ref{descr-stats}, \@ref{meta-est}, issue here: https://github.com/many-speech-analyses/many_analyses/issues/179
- The "This analysis was not preregistered and should thus be interpreted with caution" seems a little extreme, no? Given the justification/explanation just prior it seems like saying it is not pre-registered is enough (IMO). 
- I added a bit more in the part about family-wise error corrections (I wanted to mention power):  
"When operating within the frequentist inferential framework, testing the same hypothesis with different dependent variables is known to increase the false-positive (Type-I error) rate. The standard solution to this problem is to apply a correction for family-wise error (i.e., alpha inflation), which consequently reduces power."
