### ISSUE TITLE
Descriptives calculation question

### ISSUE THREAD

**Issue by jvcasillas** [many-speech-analyses/many_analyses#168]
A lot of the descriptives that were already included in the prose of the manuscript came from the tibble `msa_models_unique` which is derived from the following code on line 644 of `Draft_RR.Rmd`: 

```
msa_models_unique <- msa_models %>%
  select(animal, model_n, outcome, typicality_operationalization, framework, model, temporal_window, random_effects, n_random, phon_rating, stat_rating, n_predictors, pop_pred, operationalisation, operationalisation_notes) %>%
  distinct()
```

My question, why are we using `distinct` here? This reduces the original tibble of 170 rows to 104. The `msa_models` tibble is everything included in the meta-analysis, correct? If for example, we use the `msa_models_unique` tibble we are misrepresenting some of the values that are hand calculated and reported in prose. For example, the percent of models including duration is calculated as 35% using `msa_models_unique` (reported in prose), but 33% in the table (calculated using `msa_models`). So, the issue here is simply to double check that we want `msa_models_unique` and not `msa_models`. If the former is the correct one, the tables have to be rerun using `msa_models_unique` (simple fix). If the latter, all the derived measures need to be rerun... which brings me to the next issue...
 
As of now, the descriptives that are included in prose are calculated separately and included with inline r chunks, i.e., `round(outcome_n[[1,1]],2) * 100`. I think it makes more sense to create a tibble that includes everything (the same tibble we include as a table in the manuscript) and then pull values from the tibble in prose. This makes the code much cleaner and insures that we are calculating the same values. I have written a function to do this, `pull_from_tib`, with an example of how it work on line 922. This makes for a much cleaner document and insures we are reporting the same value everywhere it is reported.

**Comment by troettge** [comment]
Not quite sure I completely understand but it looks like an issue I brought up before: msa_models contains all coefficients including two separate coefficients of models that ran with typicality as categorical. So you have two rows corresponding to the atypical and the medium coefficient of the same model. Using that, obviously doubles a lot of counts for the proportions. I brought that up before and I think the code you refer to is Stefano's fix for that. There is also a comment of mine in the draft that asks to check if this is now the baseline for all proportions reported in prose (I suspect we have not fixed that yet). 

Does that make sense @jvcasillas ?

**Comment by jvcasillas** [comment]
Yes. Makes sense. Updating now. thanks.
