### ISSUE TITLE
Discussion - naming the dropped-out coordinator's quote

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#174]
First, I would like to discuss the inclusions, phrasing and position of the quote from one of the team coordinators. I understand that he (?) allowed us to share this quote, but I think naming names does probably not add anything to the message. It can however be perceived as finger pointing. Easy fix: remove the name. 

Second, mentioning this point where it is mentioned right now strikes me as a little out of place. Would it be possible to move this to the section in the discussion where we talk about the model plurality maybe? What do you guys think?

**Comment by stefanocoretta** [comment]
The person explicitly asked to be named when I asked for permission. Feel free to change anything as you see fit.

**Comment by troettge** [comment]
I moved it into the discussion where it really neatly fits into the argument (removed the name)
