### ISSUE TITLE
Update OSF and GitHub repo docs

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#177]
- [x] Update GH Readme with overview and link to OSF repo.
- [x] Update GH Pages with rendered HTML files for easy linking in RR. (Now the simulation code is in the github.io website).
- [x] Update OSF Wiki. State license.

**Comment by jvcasillas** [comment]
@stefanocoretta GH Pages refers to https://github.com/many-speech-analyses/many-speech-analyses.github.io, right? Which files need to be linked? What is the workflow here?

**Comment by stefanocoretta** [comment]
The spice must workflow.
