### ISSUE TITLE
Crossrefs for subsections don't render

### ISSUE THREAD

**Issue by jvcasillas** [many-speech-analyses/many_analyses#179]
Crossrefs for subsections don't seem to work, e.g., \@ref{descr-stats}, \@ref{meta-est} render as is.

**Comment by stefanocoretta** [comment]
I guess we can fix that later

**Comment by jvcasillas** [comment]
Update: It was a silly mistake (it was written with curly braces instead of parenthesis). In either case, cross-referencing a section doesn't work with our template (when corrected it leaves a blank space). I wrote in the section name by hand (our sections don't have numbers), and put in a comment to remind us to put in the crossref at a later date. (see https://github.com/many-speech-analyses/many_analyses/commit/e91eaa3b8c9e082fcf2b30dabfc43e41bfd2cc9d)
