### ISSUE TITLE
found_effect = NAs

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#180]
I am currently playing around with some visualizations and noticed that msa_models still contains NAs in found_effect column. I updated the Gsheet and added all of those values a week or two back. Could it be that the sheet was not pulled again to update table?

**Comment by jvcasillas** [comment]
The Rmd file should source the google sheet every time it's rendered. Can you double check that the sheet still has the additions you made? Maybe find a couple specific teams and I'll play with it a bit too.

**Comment by troettge** [comment]
just checked, the sheets does not have these values anymore. That is more than strange, because I went through them all manually and added them. I am not aware of google rolling back documents, are you?

It's a [to-do](https://github.com/many-speech-analyses/many_analyses/issues/181) then.

**Comment by jvcasillas** [comment]
That's obnoxious. We should be able to roll back to the version that had it, i think.

**Comment by stefanocoretta** [comment]
Just checked. You can check doc history, but there doesn't seem to be a version in which all analyses were coded for `found_effect`. In any case, we should not restore the entire document, because that will overwrite the latest changes (it's possible to copy paste though).

OR maybe it is that some in the older versions were not coded because they are the excluded ones. I can't really tell coz the order changes in different versions.

**Comment by stefanocoretta** [comment]
@troettge was this resolved?

**Comment by troettge** [comment]
@stefanocoretta ugh i don't think so (sorry about that). So we have to look into these again and complete the column in the sheet. I think these are your analyses that need coding. I won't have time for this over the weekend. Tomorrow I get my Macbook back and will probably spent the weekend to get it set up again. If you do not have time to do it, I can see if I can find time next week.

**Comment by stefanocoretta** [comment]
No problem! I will see if I can do this today. I am working on #239 now

**Comment by stefanocoretta** [comment]
I fixed this @troettge. Can you update the plots? You want to pull my branch into yours first.

**Comment by troettge** [comment]
the plots do not display which teams claimed effects, this should only affect the numbers in text. So I consider this closed then I guess (unless I missed something)
