### ISSUE TITLE
To Do after team feedback

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#181]
**Analysis**
- [x] Re-add missing found-effect values #180 

**Document**
- [x] integrate all low-level suggestions and correction
- [x] collect content comments and questions
- [x] discuss content comments and questions among SC, JC, TR
- [x] curate Tenzing roles

**Comment by jvcasillas** [comment]
Funding info: 

- Jalal Al-Tamimi, Emmanuel Ferragne, Coline Caillol, Maud Pelissier. 
    - "Partial support by the French Investissements d’Avenir - Labex EFL program (ANR-10- LABX-0083), contributing to the IdEx Université Paris Cité - ANR-18-IDEX-0001".

**Comment by jvcasillas** [comment]
@troettge @stefanocoretta draft comments are extracted and available in the google sheet (via https://github.com/many-speech-analyses/many_analyses/tree/jvc-revisions). See [08_draft_comments](https://github.com/many-speech-analyses/many_analyses/blob/jvc-revisions/scripts/r/08_draft_comments.Rmd) (and check out the knit html file).
