### ISSUE TITLE
ICPhS papers

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#182]
Deadline for submission is 1st Dec. I would like to write at least one paper about MSA. 

Here are some ideas, what do you think?
1) Summary of MSA results with focus on measures?
2) Experience with BigTeam Science in Phonetics?

3) What and how do people exclude in their analyses?
4) Pseudoreplication in phonetics. Do people account for dependencies?

no3 and no4 would require more analyses.

**Comment by stefanocoretta** [comment]
They all sound fun! I definitely won't have research time to spare until at least January, so I am happy with anything you guys decide to do.

**Comment by jvcasillas** [comment]
2 and 4 jump out to me as being more fun (right now anyway).
