### ISSUE TITLE
Reference suggestion & typo

### ISSUE THREAD

**Issue by johannacronenberg** [many-speech-analyses/many_analyses#183]
https://github.com/many-speech-analyses/many_analyses/blob/be80ab3112f04a433036182dffb755178e3096cc/RR_manuscript/Draft_RR.tex#L74

Suggestion: for "forking paths" and "garden of analytic choices", cite e.g. Gelman & Loken (2014) or other papers which use these coined terms

Typo: "than what previously observed" --> "than was previously observed"

**Comment by jvcasillas** [comment]
Typo fixed via https://github.com/many-speech-analyses/many_analyses/pull/236/commits/d251b8f3992e09f8bf8530f2b05322a464849699
