### ISSUE TITLE
Use plural noun and verb?

### ISSUE THREAD

**Issue by johannacronenberg** [many-speech-analyses/many_analyses#189]
https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.tex#L519

I'm not sure about the use of singular vs. plural in this sentence, i.e. I would prefer: 
"The outcome variables of the model were the standardized effect sizes and the related standard deviation."

**Comment by jvcasillas** [comment]
Fixed via https://github.com/many-speech-analyses/many_analyses/pull/236
