### ISSUE TITLE
vs. versus vs

### ISSUE THREAD

**Issue by johannacronenberg** [many-speech-analyses/many_analyses#191]
https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.tex#L164

Currently, you use two abbreviations of "versus": "vs." and "vs". Maybe settle on one of them.

**Comment by jvcasillas** [comment]
Changed to `vs.` throughout via https://github.com/many-speech-analyses/many_analyses/pull/236
