### ISSUE TITLE
Word unclear / typo

### ISSUE THREAD

**Issue by johannacronenberg** [many-speech-analyses/many_analyses#193]
https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.tex#L742

"affects the analysts estimate": I am not sure whether you meant "analysts'", "analytic", or maybe "model"?

**Comment by jvcasillas** [comment]
Left as `analysts'` (previously fixed via https://github.com/many-speech-analyses/many_analyses/pull/236)
