### ISSUE TITLE
Use more general term?

### ISSUE THREAD

**Issue by johannacronenberg** [many-speech-analyses/many_analyses#203]
https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.tex#L907

"speech or video signals" --> "audio or video signals"? I think your results are also informative to people who work with audio (not just specifically speech) signals.

**Comment by jvcasillas** [comment]
Fixed via https://github.com/many-speech-analyses/many_analyses/pull/236
