### ISSUE TITLE
Wording in abstract

### ISSUE THREAD

**Issue by roryturnbull** [many-speech-analyses/many_analyses#205]
Not clear to me if "that derives" refers to "nature of speech" or to "analytic approaches". If the latter, I think it should be "derive"; if the former, I'd suggest a slight restructuring to avoid ambiguity: "...in analytic approaches, which derives..."

https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.Rmd#L22

**Comment by jvcasillas** [comment]
Fixed via https://github.com/many-speech-analyses/many_analyses/pull/236
