### ISSUE TITLE
(More) wording in abstract

### ISSUE THREAD

**Issue by roryturnbull** [many-speech-analyses/many_analyses#206]
The final clause of the abstract is unclear whether this (little effect of analytic and researcher-based predictors) is good or bad news. The beginning of the abstract prepares the reader for bad news in relation to variation across methods and conclusion, but this line strikes me as potentially positive news.

https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.Rmd#L22

**Comment by troettge** [comment]
reworked abstract
