### ISSUE TITLE
missing word

### ISSUE THREAD

**Issue by roryturnbull** [many-speech-analyses/many_analyses#207]
should be
"...higher degree of variability across analysts than what *was* previously observed,..."

https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.Rmd#L118

**Comment by jvcasillas** [comment]
Fixed via https://github.com/many-speech-analyses/many_analyses/pull/236
