### ISSUE TITLE
reference needed

### ISSUE THREAD

**Issue by roryturnbull** [many-speech-analyses/many_analyses#217]
A reference here for this point would be good - focus marking can be, perhaps not surprisingly, very different from language to language.

Burdin et al. 2015 and Matic & Wedgwood 2013 are good references for this:

@article{matic2013meanings,
  title={The meanings of focus: The significance of an interpretation-based category in cross-linguistic analysis1},
  author={Mati{\'c}, Dejan and Wedgwood, Daniel},
  journal={Journal of Linguistics},
  volume={49},
  number={1},
  pages={127--163},
  year={2013},
  publisher={Cambridge University Press}
}

@article{BURDIN2015254,
title = {Variation in the prosody of focus in head- and head/edge-prominence languages},
journal = {Lingua},
volume = {165},
pages = {254-276},
year = {2015},
note = {Prosody and Information Status in Typological Perspective},
issn = {0024-3841},
doi = {https://doi.org/10.1016/j.lingua.2014.10.001},
url = {https://www.sciencedirect.com/science/article/pii/S0024384114002290},
author = {Rachel Steindel Burdin and Sara Phillips-Bourass and Rory Turnbull and Murat Yasavul and Cynthia G. Clopper and Judith Tonhauser}

https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.Rmd#L304

**Comment by jvcasillas** [comment]
Added via https://github.com/many-speech-analyses/many_analyses/pull/236
