### ISSUE TITLE
elaboration on ecological validity

### ISSUE THREAD

**Issue by roryturnbull** [many-speech-analyses/many_analyses#220]
"let them analyze the data as they saw fit"

This is where we're reminded of some of the unusual nature of this task, from the perspective of an analyst. The exhortation to "do whatever you want, go crazy!" may have led some teams to take a "measure everything that moves" approach, or a more risky or unusual analysis than they'd normally do on their own projects. There's also the fact that most teams are (presumably?) not quite as invested in this project as they are with their own research - in other words, there is no temptation for p-hacking here, although there is an incentive to do so for most projects. Coupled with the fact that the analysts had no control over the data collection, many teams may have carried out analyses quite different from their "standard" procedure. These points should be highlighted somewhere - I don't think they detract from the main message of the paper, but they're worthwhile considerations.

https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.Rmd#L330

**Comment by troettge** [comment]
addressed by mentioning of anti-coordination approaches
