### ISSUE TITLE
table error

### ISSUE THREAD

**Issue by roryturnbull** [many-speech-analyses/many_analyses#229]
The table as displayed says "phd" rather than "PhD"
https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.Rmd#L990-L1059
it looks like the label is defined earlier:
https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.Rmd#L810
So this might be a rendering issue where all labels are converted to Sentence case? Perhaps the capitalization can be protected by enclosing it in curly brackets or something? I'm not familiar with these packages, sorry.

**Comment by jvcasillas** [comment]
Fixed via https://github.com/many-speech-analyses/many_analyses/pull/236
