### ISSUE TITLE
typo / inconsistency

### ISSUE THREAD

**Issue by roryturnbull** [many-speech-analyses/many_analyses#231]
should be "researcher degrees of freedom" for consistency
https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.Rmd#L1359

**Comment by jvcasillas** [comment]
Fixed via https://github.com/many-speech-analyses/many_analyses/pull/236
