### ISSUE TITLE
overstating the case

### ISSUE THREAD

**Issue by roryturnbull** [many-speech-analyses/many_analyses#234]
This is true, but the great majority of teams came to the same conclusion. Only the ones at the tails of the distribution disagreed. I'm curious if those outlier analyses would have survived peer review if they were part of a "real" study; how were those outlier analyses rated by the analyst team reviews?

https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.Rmd#L1439

**Comment by troettge** [comment]
addressed
