### ISSUE TITLE
a more optimistic outlook

### ISSUE THREAD

**Issue by roryturnbull** [many-speech-analyses/many_analyses#235]
another way to see it is that the teams did a good job at over-coming bias and degree of experience in what they produced. they chose very different variations of the same broad acoustic methods, and the conclusions were largely the same by the large majority of them but some teams did arrive at conclusions that were the opposite ends of the yes-no continuum

https://github.com/many-speech-analyses/many_analyses/blob/fe737878f3b06e12099a0a41a76d64a983a4698a/RR_manuscript/Draft_RR.Rmd#L1448-L1451

**Comment by troettge** [comment]
adressed
