### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#238]
Generally I think, integrating spelling/grammar/formulation comments is straightforward and can be done by one person who makes execute decisions. Naturally I am thinking of @jvcasillas because he is the only native speaker. I completely trust you judgement there. But we can also split it up, because there are a lot of suggestions. What do you think?

**Comment by jvcasillas** [comment]
Fixed via https://github.com/many-speech-analyses/many_analyses/pull/236/commits/82f9e26572c74aa59c27fb6b2d79ae5a1c2cdee0 and https://github.com/many-speech-analyses/many_analyses/pull/236/commits/d251b8f3992e09f8bf8530f2b05322a464849699
