### ISSUE TITLE
Number of teams 46 vs 30

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#239]
Timo: number of teams/analysis was unclear and the exclusions criteria for going from 46 to 30 were unclear. I agree and I suggest actually to include the descriptive stats for all 46 analysis teams up until our description of the statistical part. The exclusion of analyses was done only for the meta analyses and should not affect the descriptive part IMO (like team properties and measurement properties). There were 46 teams afterall and that is a strength of the paper that we kind of swept under the rug by focussing to much on the 30 teams we used for the meta-analysis.

Type of descriptive stats in the descriptive part of the results is sometimes questioned. We could have a look at that and try to use more appropriate descriptors (e.g. median instead of mean, etc.)

**Comment by stefanocoretta** [comment]
- [ ] Try to reshape table so that it has values from both the 46 and 30 teams.
- [ ] Use range and median/mode.
- [ ] If table becomes too busy with both 46 and 30, then just leave one in appendix and link it in the text.

**Comment by stefanocoretta** [comment]
Thanks for your edits, @jvcasillas! I think it is fine to leave the table as is (only with data for the 30 teams) and link to suppl materials for the 46 teams.

I have updated the relevant code and sections in 4da511f (my own branch), but I am not sure why there are still some values for the median that have decimals that are not `.5` (with median that should not happen, right?). Could you check to see why some of the medians have decimals other than 0.5?

**Comment by troettge** [comment]
make sure to justify the exclusion from 46 to 30 very clearly

**Comment by jvcasillas** [comment]
This seems to be working fine. There are values that aren't .5, but that is because when there is an even number of values the `median` function averages between the two medians. You won't get a perfect whole number or a .5 if the two medians aren't integers, e.g., 1, 3.2, 5.1, 10... median = 4.15 (remember a lot of the values we are looking at are team averages, like years since finishing the phd).
