### ISSUE TITLE
take out discussion of meta-analytical estimate

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#245]
The meta analytical estimate is basically meaningless, given that the scale is not interpretable and artificial negative and positive estimates cancel each other out. I wonder whether we should take this out  short paragraph in the "### Meta-analytic intercept
" out (or footnote it). Alternatively we could qualify it by saying it is meaningless, but then again, why would we present something to the reader that is in fact irrelevant and not interpretable?

Opinions?

**Comment by stefanocoretta** [comment]
I have kept it but added a blurb. Since it's work we have put in and since it's something we have pre-registered I think it's better to keep it. See 8ba5d53
