### ISSUE TITLE
Address remaining comments on gdoc and GH issues

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#247]
I have pushed my changes (PR [here](https://github.com/many-speech-analyses/many_analyses/pull/246)). 

I worked through most remaining comments in the gdoc and resolved them in this [copy](https://docs.google.com/document/d/1OEPLUSy6DJxg-NBRoVWSQZ2iDu9iRf15-MRYLKWZO7o/edit#). 

I left a bunch of them for several reasons
- related to the to dos assigned to one of your (e.g. the team numbers)
- I have worked on addressing but feel like you need to evaluate it for yourself (and possibly address it)
- I was unsure whether you find it worthy to address or unsure what to do about it
- left for discussion

So I suggest the following: 

- [ ] check my edits and edit/delete/complement as you see fit
- [ ] go through the remaining comments and resolve those which you feel like can be ignored, have been addressed sufficiently or you address yourself

How does that sound?

**Comment by stefanocoretta** [comment]
Had a look at the PR, seems all good to me, expect the example with IQ that I don't think is relevant (better to just give the same example we give later, with vowel duration, saying that we discuss the full derivation later). and I think this should be as soon as we present the estimates of model/team variability.

**Comment by stefanocoretta** [comment]
I see that the comments from Rory are still open issues. Were they addressed?

**Comment by jvcasillas** [comment]
The issues brought up by Rory that haven't been closed are all conceptual or food for thought type comments. I fixed and closed all issues related to typos/clarity/etc. I didn't want to close the others because I didn't/don't know if you both have read them (they deal with issues that were brought in the google doc)

**Comment by stefanocoretta** [comment]
Sorry I am not sure I understand. Does that mean that there are issues on the google doc I should be looking at?

**Comment by jvcasillas** [comment]
Yes? When I say issues I mean comments. Comments that other people made in the google doc.

**Comment by stefanocoretta** [comment]
And what about Rory's comments which are issues on the repo?

**Comment by jvcasillas** [comment]
So at this point you and @troettge need to read them if you haven't. Timo, check and see if the comments were already covered in the revisions added in your last PR. If so, close those issues. Whatever is left, we should discuss and distribute.

**Comment by troettge** [comment]
I have read them and some might be addressed but there are still great points that could be better addressed IMO. Haven't worked on them directly and I unfortunately won't have resources for editing next week, so please take over and make executive decisions on them. Ideally distill a set of remaining comments that you feel unsure about or need input and then let's briefly discuss them via meeting, so we can finally sent this off. A heads-up: I will be super busy with teaching and presentations in November.
