### ISSUE TITLE
CRediT taxonomy: two scripts

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#250]
There are two scripts for the CRediT taxonomy:

- `00_credit_taxonomy.R`
- `09_credit_taxonomy.Rmd`

Can we delete the first?

**Comment by jvcasillas** [comment]
Yes! The `09_credit_taxonomy.Rmd` doesn't save the figures, so if we plan on using them we will need to do that, but the `00` script can safely be removed.

**Comment by stefanocoretta** [comment]
OK! I will add ggsave in 09 and delete 00 now! :)

**Comment by stefanocoretta** [comment]
Trying to run 09 but I don't have the right permissions to run the drive thingies. Ideas, @jvcasillas ?

**Comment by jvcasillas** [comment]
Hmm I'm not sure. What error does it give you? I ran it all in the console as I was writing the code so I gave permission that way. I bet it probably cached something so that it didn't have to ask when I knit. Did you try running it to the console first?
