### ISSUE TITLE
discuss example of same-ish analytical path resulting in different estimates

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#252]
I tried to find an example of an analysis choice that resulted in different estimates: Got 6 teams analysing f0 in the adjective with typicality as categorical predictor. 

`"T050" "T019" "T059" "T009" "T061" "T015"`

Estimates for the coef for "typical" range from -0.11 to 0.38.

Ratings for these analyses range from 66-89 (stats), and 66-86 (phon)

I was wondering whether we could discuss this to give some additional evidence that even if they chose to measure the same outcome in the same domain, they result at different estimates (one of them actually claim an effect). This would be powerful to counter the main concern of authors that people "just" answered different questions. 

Look at subset: 

`msa_models_sub <- msa_models %>%
  filter(outcome %in% c("f0")) %>%
  filter(typicality %in% c("categorical")) %>%
  filter(typ_level %in% c("typical")) %>%
  filter(temporal_window %in% c("word")) %>%
  filter(specific_domain %in% c("adjective")) %>%
  filter(exclude %in% c("no")) %>%
  #filter(found_effect %in% c("yes")) %>%
  select(team, estimate, se, outcome, temporal_window, specific_domain,
         typicality, typ_level, operationalisation, found_effect, 
         prior_belief, phon_rating, stat_rating)`

**Comment by stefanocoretta** [comment]
This seems very nice!

**Comment by troettge** [comment]
An attempt to draft a paragraph:

"By choosing different outcome variables or choosing different measurement windows, analysts arrived at very different effect estimates. While one might find it obvious that measuring different parts of the speech signal leads to different results, the fact that analysts (and reviewer alike) considered all these choices valid ways of answering the same research question points to a lack of theoretical consensus on what aspects of the speech signal correspond to what types of communicative functions. Importantly, even if analysts choose to measure more or less the same acoustic property within the same measurement window, they arrive at different estimates: For example, six teams measure f0 in the adjective, using typicality as a categorical predictor. Their standardized effect estimates ranged from -0.11 to 0.38 standard deviations. While these teams in principle measured the same thing, they differed in analytical details of how f0 was operationalized (mean, min, max, range, etc.) and how their statistical model was constructed (number of predictors ranged from 1-3, number of random effect terms ranged from 1-4). As shown by Breznau et al. (2021), even these seemingly inconsequential analytical choices can affect conclusions in non-trivial ways."

**Comment by troettge** [comment]
added to MS on my branch
