### ISSUE TITLE
Tenzing not yet corrected

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#266]
It is common practice to "correct" the self-claimed contributions. I would suggest we do that. I have hand-corrected them in a separate [sheet](https://docs.google.com/spreadsheets/d/1lXmubF42sTCoOaECXGzo20GCFxX51MWFOKhX8euNtuA/edit#gid=1654812123)

I removed ticks for funding, conceptualisations and original draft. The corrected table needs to processed again for the figure.

**Comment by troettge** [comment]
Looking at the [graph](https://github.com/many-speech-analyses/many_analyses/blob/main/figs/credit-taxonomy.png) we have linked in MS, the graph does not even match the tenzing table. Please check

**Comment by stefanocoretta** [comment]
@troettge can you have a look at it?

**Comment by troettge** [comment]
> @troettge can you have a look at it?

@jvcasillas made the graph and extracted the data, so probably much easier for you?

**Comment by jvcasillas** [comment]
What exactly doesn't match? @troettge Do you mean after you edited the document?

**Comment by troettge** [comment]
@jvcasillas the column names must be off? The [figure](https://github.com/many-speech-analyses/many_analyses/blob/main/figs/credit-taxonomy.png) shows for example a lot of filled dots in conceptualization and first draft. There were some folks who did that but not the majority. Or am I missing something here? Also the manually corrected sheet should be pulled in (the second sheet I created).

**Comment by jvcasillas** [comment]
I see now. This should be fixed via https://github.com/many-speech-analyses/many_analyses/pull/273

You can see the current plot [here](https://github.com/many-speech-analyses/many_analyses/blob/jvc-revisions/figs/credit-taxonomy.png)

It looks right to me and seems to check out, but would be good to get another pair of eyes on it just in case.

**Comment by troettge** [comment]
@jvcasillas please let me know what I am missing but just looking into the first column of that figure, the figure does not make sense to me. Something must go wrong there, e.g. Conceptualization by RR, MR, GM, AS and AL???

**Comment by jvcasillas** [comment]
Ok. I think I understand the issue. You created a copy and then edited the copy, right? The document still pulls in the original copy (which also says you edited it two days ago). Generally, I think it is a mistake to create copies of a document that already tracks changes. It creates confusion for us and anybody who come back to look at this. I will adjust the script to pull in the new document, but we are going to have to log this somehow so that people checking the repo will know what is going on.

**Comment by jvcasillas** [comment]
Problem... the old version and the new version seem to have the same google id so Im not sure how to pull the newer one from R. @stefanocoretta @troettge do either of you know how to do this using googlesheets? I cant find anything in the documentation.

**Comment by troettge** [comment]
We could simply copy the two sheets into separate files?

**Comment by jvcasillas** [comment]
Ok. I'm at a conference. I will do this tonight or tomorrow morning and update.

**Comment by jvcasillas** [comment]
Ok I htink were good to go! Double check here: 
![](https://github.com/many-speech-analyses/many_analyses/blob/jvc-revisions/figs/credit-taxonomy.png)

**Comment by troettge** [comment]
@jvcasillas don't see us in there :(

**Comment by jvcasillas** [comment]
Youre look at the plot of the analysts. 

We live overhere: https://github.com/many-speech-analyses/many_analyses/blob/jvc-revisions/figs/credit-taxonomy-initiators.png

**Comment by jvcasillas** [comment]
I can put us all together. Not sure why I did it this way initially.

**Comment by troettge** [comment]
oh, sorry i was not aware that there are separate figures. And I would not agree that Simon Roessig and Michael Franke are initiating authors. Should be all in one IMO, no categories, just the Credit roles.

**Comment by jvcasillas** [comment]
Initiators: https://github.com/many-speech-analyses/many_analyses/blob/jvc-revisions/figs/credit-taxonomy-initiators.png
Analysts: https://github.com/many-speech-analyses/many_analyses/blob/jvc-revisions/figs/credit-taxonomy-analysts.png
All: https://github.com/many-speech-analyses/many_analyses/blob/jvc-revisions/figs/credit-taxonomy-all.png

**Comment by jvcasillas** [comment]
Ok. Let's just pretend that one doesn't exist. One plot of everybody, in alphabetical order?

**Comment by jvcasillas** [comment]
Assuming the above is ok, this is hte final plot: https://github.com/many-speech-analyses/many_analyses/blob/jvc-revisions/figs/credit-taxonomy-all.png

**Comment by stefanocoretta** [comment]
What if instead of having a figure we just link to the sheet since there are so many authors?
