### ISSUE TITLE
Revision Letter

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#267]
Need to draft revision letter in which we explain the files that we upload (including the draft_diff etc), justify changes to the analysis briefly and point to detailed change-log.

**Comment by troettge** [comment]
Starting to draft [here](https://docs.google.com/document/d/1QsvUnrnTgUV6TQtmi2aM9IOIQUVvmZxEYPFVdNCip1A/edit).

**Comment by stefanocoretta** [comment]
Looks good to me!

**Comment by stefanocoretta** [comment]
@troettge add note that we update authors and affiliations later
