### ISSUE TITLE
justify all changes in change log

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#269]
the change log still contains unjustified changes, e.g. "Decided to drop last round of review with all analysis plus revision of review". I think it might be safer to add some justification to all decisions, even if they refer to lack of resources or time. What do you think?

**Comment by stefanocoretta** [comment]
Yeah sounds good to me! :) go ahead @troettge

**Comment by stefanocoretta** [comment]
Yes!

**Comment by jvcasillas** [comment]
Seems good to me. Do we want to keep the changes to the change log (the text with the strike)? Super meta.

**Comment by stefanocoretta** [comment]
Yeah I would keep it because it shows progression of thought

**Comment by stefanocoretta** [comment]
I think we can now close this?

**Comment by jvcasillas** [comment]
All good on my end. 👍🏼

**Comment by jvcasillas** [comment]
On second thought... it probably makes sense to also explain the copies of the google doc version of the manuscript and the CReDIT taxonomies.
