### ISSUE TITLE
supp materials

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#270]
MS states: "A complete summary of all the analyses from the 46 submitting teams is available in the supplementary materials". There is no link. Where can the reader find this information (I assume the table with values for all 46 teams)?

**Comment by jvcasillas** [comment]
Good catch. Is this document to be uploaded to the OSF separately? Or should we include it at the end of the RR (and just call it an appendix)?

**Comment by troettge** [comment]
It's kind of a super important table, I vote for appendix, but have no strong feelings either way

**Comment by stefanocoretta** [comment]
Isn't this among the scripts in the scripts folder? I would just link to it in the manuscript as we did with the other scripts.

**Comment by jvcasillas** [comment]
its `supplementary_materials.Rmd` in the `RR_manuscript` folder.

**Comment by jvcasillas** [comment]
Stef, whatever changes you made to the code for the table in the main rr .Rmd file need to be applied to the table in `supplementary_materials.Rmd` as well. Was it just changing `mean` to `median`?

**Comment by stefanocoretta** [comment]
Ah that's why I couldn't find it in scripts ahahah. It's fine, we can leave it in there or I'll move it.

Yes I think what I did was just to use the median and range instead of mean and SD

**Comment by stefanocoretta** [comment]
@jvcasillas let me know when you have changed the file and I'll add the link to it in the RR.

**Comment by jvcasillas** [comment]
Updated via https://github.com/many-speech-analyses/many_analyses/pull/273
