### ISSUE TITLE
Stage2-Review

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#282]
Julia Strand
- [x] #295
- [x] #296
- [x] add analyses as component ? to OSF @stefanocoretta 
- [x] clarify how we extracted standardized effect sizes (p.24, bottom) --> Not sure I know what to do because it is pretty clear to me
- [x] possibly outsourcing detail in manuscript about model fitting? (p.28, ll18ff) Joseph / Timo vote to keep it
  - [x] We decided to keep it.
- [x] exclusion criteria of teams preregged if not make explicit @troettge 
- [x] was there something systematic about excluded teams? --> just answer "not to our knowledge"
- [x] visually distinguish between different types of predictors in forest plot @troettge
- [x] expand on preregistration in reform paragraph @troettge --> actually now that I think about it, it does not fit well into the narrative. Prereg does not change the issue at hand, that individual researchers come up with different ways to answer the same question.

Matt Goldrick

- [x] add information about the handling of divergent transitions in ms (bff7a21, 9673ed4)
  - #288 
- [x] details to minor divergences between RR and Stage2 MS
- [x] make gdocs (change logs, commented ms etc) publicly available @stefanocoretta 
  - [x] https://drive.google.com/drive/folders/1-DOcj1qtEkvWfzu_FrsxkIGfPS0DyLXB?usp=sharing
  - [x] Need to be added in RR (bff7a21)
  - [x] Added to OSF Wiki.
- [x] add changes to refitting procedure to change log and ms (note on change of treatment coding?) (bff7a21)
- [x] typos: Page 28: last sentence of first paragraph "this we decided against"-> thus we decided against @stefanocoretta 
- [x] Page 31: Second paragraph under "statistical analysis" -- r code shown, rather than upper value of range @stefanocoretta 
- [x] Third full paragraph "are relateD to mathematically formalizing verbal…" @stefanocoretta 
- [x] It might be good to note that mathematical/computational modeling, while important, currently works in spaces that are much lower in dimensionality than the system we are measuring. We are still stuck with the issue of how to relate an abstract modeling space to the measurement space. @troettge 
- [x] CReDIT URL should be: https://github.com/many-speech-analyses/many_analyses/blob/main/figs/credit-taxonomy-all.png @stefanocoretta 

Misc

- [x] Shiny @jvcasillas 
  - [x] Look pretty
  - [x] color code by outcome measure/temporal window/operationalization and typicality operationalization
  - [x] add panel with scatter plot of effect size and continuous predictors
  - [x] add link to manuscript? @jvcasillas

**Comment by jvcasillas** [comment]
Notes:

- Add codebook to OSF? Make component of meta-analysis?
- Generally need to tidy up and make sure it is easy to follow

**Comment by stefanocoretta** [comment]
For the analysis OSF component, I did this:

- I created a `Meta-analysis` component.
- I linked the GitHub repo to that component.
- I removed the link to the GitHub repo from the main component and updated the main Wiki to reflect the change.

**Comment by troettge** [comment]
@stefanocoretta @jvcasillas please add your responses to the [response letter](https://docs.google.com/document/d/1sFM5SQsV0X0P_pgnsUAEoHTdA-oYRpixJj-Dr8ZlKEM/edit) as you see fit:

**Comment by stefanocoretta** [comment]
The [response letter](https://docs.google.com/document/d/1sFM5SQsV0X0P_pgnsUAEoHTdA-oYRpixJj-Dr8ZlKEM/edit) is almost complete. @jvcasillas just needs your input.

**Comment by jvcasillas** [comment]
Input added!
