### ISSUE TITLE
flow chart 

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#284]
comments on flow chart. Regarding color scheme: I used the orange from fig 3 and used complementary colors

![image](https://user-images.githubusercontent.com/13022447/210743723-17762a00-7544-4bd0-b91b-17ca3a575b73.png)

**Comment by troettge** [comment]
5-color contrasts with qualitative colors contrasts is very difficult

**Comment by troettge** [comment]
alternative color scheme
![image](https://user-images.githubusercontent.com/13022447/210745604-a2f63342-d3b6-4338-9164-b3c0e961cf09.png)

**Comment by jvcasillas** [comment]
I think I definitely prefer the suns themed colors over the xmas colors. With regard to your question, I'm not sure about "unclear" but I assume "point" just means they measured the duration and submitted a single data point per item or whatever. Looking at the plot, "point", "relation" and "unclear" seem to be the only possibilities, right? How else would you do it?

**Comment by jvcasillas** [comment]
Also, in the second plot, the colors coming out of the options on the left dont match with the actual colors in the "what" block. For example, the "intensity" block is red, but the colors coming out are green.

**Comment by stefanocoretta** [comment]
I prefer the first plot colour scheme. The second one is not colour blind friendly.

<img width="892" alt="Screenshot 2023-01-06 at 15 42 49" src="https://user-images.githubusercontent.com/6429302/211046275-9198f0a5-0f44-4e8d-a788-826688887044.png">
<img width="1034" alt="Screenshot 2023-01-06 at 15 42 41" src="https://user-images.githubusercontent.com/6429302/211046289-464e7455-0ca5-4da2-b139-4f09778c7184.png">

**Comment by jvcasillas** [comment]
I guess (a) makes the most sense in hindsight. The major consequences... all of the reported values (in prose and in tables) would be different, but that would be taken care of when we reknit the document, right? @stefanocoretta can you think of anything else downstream that would have to be fixed?
