### ISSUE TITLE
ordered forest plot

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#285]
Okay?

![image](https://user-images.githubusercontent.com/13022447/211524891-fa07ebfb-0e8f-4c48-932e-371c12880f8f.png)

**Comment by stefanocoretta** [comment]
Beautiful!

**Comment by jvcasillas** [comment]
Looks great. Would it be possible to capitalize the labels?

**Comment by troettge** [comment]
What labels? The y-axis labels?

**Comment by jvcasillas** [comment]
The y-axis in plot C and the x-axis in A and B.

**Comment by troettge** [comment]
oh I get it now, you mean capitalize first letter. I somehow thought all-cap them. Got ya
