### ISSUE TITLE
Acknowledgments

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#286]
Need to add acknowledgements.

We would like to thank the editors David Sbarra and Julia Strand, Matthew Goldrick and two anonymous reviewers for their insightful comments and suggestions. 

This project was partially supported by the European Research Council Grant No. 742289 *Human interaction and the evolution of spoken accent* (2017–2022) awarded to Prof. Jonathan Harrington (author SC).

[FUNDING INFOS]

All remaining errors are the initiating authors' (SC, JC, TR)

**Comment by stefanocoretta** [comment]
@jvcasillas do you have any funding info to add?

**Comment by jvcasillas** [comment]
I have no funding info to add.
