### ISSUE TITLE
Get range of divergent transitions in refitted models

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#288]
https://github.com/many-speech-analyses/many_analyses/blob/bff7a21617bef63a3c5b7340daddec668c636cb4/RR_manuscript/Draft_RR.Rmd#L1049

Joseph, can you please get the range of div transitions of the refitted models? I remember you said there's code in one of your scripts that can get that info.

**Comment by jvcasillas** [comment]
Of the models with divergent transitions (n = 10), the number of divergencies ranged from 1 to 143 (Note: 143 represents 3.58% of total samples).

**Comment by jvcasillas** [comment]
Added via https://github.com/many-speech-analyses/many_analyses/pull/291

**Comment by stefanocoretta** [comment]
Thanks you!
