### ISSUE TITLE
Fix sourcing of refit_jvc.Rmd in 07_teams_sd.Rmd

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#293]
https://github.com/many-speech-analyses/many_analyses/blob/9c4e42994baa17f23e78d57b5dbe103caec25581/scripts/r/07_team-sds.Rmd#L2

Cal you please make a branch off `rerun` and fix `07_teams_sd.Rmd`?

**Comment by jvcasillas** [comment]
@stefanocoretta 07_teams_sd pull from the google sheet with all of the coded analyses. Is this safe to pull from now? Is it up to date?

**Comment by jvcasillas** [comment]
Fixed via https://github.com/many-speech-analyses/many_analyses/pull/298
