### ISSUE TITLE
integrate sankey diagram (flow_outcome.png) into appendix

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#296]

**Comment by jvcasillas** [comment]
Added via https://github.com/many-speech-analyses/many_analyses/pull/298 though Im not sure if flow_outcome.png is the up-to-date version. The supplementary materials Rmd will need to be reknit after the visualization is finished.

**Comment by stefanocoretta** [comment]
Gracias jefe!
