### ISSUE TITLE
Delete `metadata` directory

### ISSUE THREAD

**Issue by jvcasillas** [many-speech-analyses/many_analyses#299]
I believe the `metadata` directory is leftover from a very early point in the history of the MSA project. I am pretty certain that the directory and the corresponding `credit-taxonomy.csv` file can be deleted. @troettge @stefanocoretta Are either of you aware of it being used anywhere? I've searched pretty much the entire project and I haven't seen the csv file being used anyway. I think we can trim the fat.

**Comment by stefanocoretta** [comment]
Yes, just checked too.
