### ISSUE TITLE
Delete `data/teams_analyses` directory

### ISSUE THREAD

**Issue by jvcasillas** [many-speech-analyses/many_analyses#300]
This directory is empty and I don't believe it was ever used.

**Comment by jvcasillas** [comment]
Not sure this directory or `metadata` mentioned in https://github.com/many-speech-analyses/many_analyses/issues/299 are available in every branch. Come back to this after everything is pushed to main.

**Comment by stefanocoretta** [comment]
I dont have teams_analyses on my fresh clone so safe for you to remove
