### ISSUE TITLE
Wrong number of teams

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#302]
https://github.com/many-speech-analyses/many_analyses/blob/109bcd18273fae97be39678d886f95528f7b6cb4/RR_manuscript/Draft_RR.Rmd#L1549

The output of that line is 32 teams included, but the `msa_models.rds` file has 33.

**Comment by jvcasillas** [comment]
Ha. Allison Hilger was the leader of two different teams. I changed the code to find unique teams based on animal name instead of team leader name. PR incoming.

**Comment by jvcasillas** [comment]
This is change is also included in `supplementary_materials.Rmd`.

**Comment by jvcasillas** [comment]
Fixed via https://github.com/many-speech-analyses/many_analyses/pull/305
