### ISSUE TITLE
Wrong number of total models

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#303]
https://github.com/many-speech-analyses/many_analyses/blob/109bcd18273fae97be39678d886f95528f7b6cb4/RR_manuscript/Draft_RR.Rmd#L1562

There are 115 models but the output says 119. I think it might be related to the multivariate models?

**Comment by jvcasillas** [comment]
It was indeed the multivariate models. Fixed via https://github.com/many-speech-analyses/many_analyses/pull/305
