### ISSUE TITLE
Link to shinyapp

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#313]
@jvcasillas says:

> Should we also link the shiny app? If so, my suggestion would be to create a page in the msa website (like https://many-speech-analyses.github.io/shiny) that is an html redirect to the real address. This way if the app ever needs to be moved/hosted somewhere else we can just adjust where the redirect points to. I can knock this out quick if we want to go this route.

**Comment by jvcasillas** [comment]
Added via https://github.com/many-speech-analyses/many-speech-analyses.github.io/commit/26cb8079367c991ab2a6d17ec3e6bc88582966ee
