### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#44]
As it currently stands, there is a mismatch between the text in the RR and the survey. But a few general questions:

- Does the rating of the overall analysis include both the measurement and the statistical parts?
- Are all ratings supposed to be a number between 0-100? Or are all ratings except the one of the overall analysis supposed to be text?
- How are we gonna use the text responses?

@troettge @jvcasillas

**Comment by jvcasillas** [comment]
I hadn't thought about point 1. I think initially we conceived of a single rating evaluating both the measurement and the statistical parts. Timo will correct me if I'm wrong. 
Regarding point 2, we should just make the ratings a number between 0-100, if that is not the case. Seems simple and uniform. 
Finally, I hadn't thought about text responses yet. Those are much more annoying. I guess we would have to read them and consider some kind of qualitative assessment on their usefulness. That's all I can think of right now, but we need to hash out these issues at our next meeting.

**Comment by troettge** [comment]
I'd say text responses we won't preregister, but will have a qualitative look at them later to learn more. Ratings, I'd also go with 0-100. I was originally thinking of asking them to evaluate stats and phonetic analysis (or choice of measurement) separately. What do you think?

**Comment by stefanocoretta** [comment]
I was thinking maybe we could have a scale for all the questions and no text responses, except maybe for just one for extra comments the reviewers might feel like adding. This would also facilitate the reviewers' job I think.

And yes, I would separate data processing/generation from statistical analyses.

**Comment by stefanocoretta** [comment]
Just to be sure, now there's only one question about acoustics and statistics on a 0-100 scale. Then all other questions are open questions with a text box, but I think it would be sensible to make those too into a 0-100 scale.

**Comment by jvcasillas** [comment]
I like that idea. Less text is better.

**Comment by stefanocoretta** [comment]
We might want to think about the questions in the peer review (I guess we can discuss it here, to speed things up a bit). Now these are the criteria for which the reviewers have to provide ratings:

* Overall appropriateness of the acoustic analysis.
* Overall appropriateness of the statistical analysis.
* Choice of statistical analysis type.
* Model variables choice.
* Model specification.
* Data exclusion.
* Data transformation.

I think we should add a few more on the acoustic analysis.

We also ask to choose one of the options for the following:

* Would the analytical methods presented produce an analysis that is:
  * publishable as is
  * publishable with minor revisions
  * publishable with major revisions
  * deeply flawed and unpublishable

**Comment by stefanocoretta** [comment]
Three Qs: acoustics, stats, overall.
Ratings + textbox.

**Comment by jvcasillas** [comment]
Updated, link here: https://rutgers.ca1.qualtrics.com/jfe/form/SV_3k5uG3oilQVMV5s

**Comment by stefanocoretta** [comment]
Great, thanks!
