### ISSUE TITLE
Typicality

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#45]
@troettge Timo, could you let me know how the typicality categories were created? I just need to know if the mean or the median (or else) was calculated for each Adj/N pair, so I can include that in the trial lists (now it has mean, sd and median).

**Comment by troettge** [comment]
This information is all in the detailed description of the experiment. It’s complicated, haha:

“Typical FOODs were defined by norming ratings above 90. Atypical FOODs were defined by norming ratings below 25. Medium typical FOODs were defined by norming ratings in between 25 and 90."
